### ISSUE TITLE
Automated builds on docker hub for nginx-php

### ISSUE THREAD

**Issue by stffabi** [motius/dockerfiles#9]
The nginx-php image on [docker hub](https://hub.docker.com/r/motius/nginx-php/) has no automated docker hub builds. At the moment it will only be updated by the circleci nightly.

Would be great to also have automated builds on docker hub.

**Comment by dgiebert** [comment]
Currently enabling the automated builds

**Comment by dgiebert** [comment]
Building the images on docker hub takes ~1h so I will disable and enable automatic builds explicitly for PR or changes concerning nginx-php

Nightly builds using circle-ci will be kept

**Comment by dgiebert** [comment]
Will close this issue for now
- nginx-php transformed into an automated build
- nightlies done using circleci
